/* Dictionnaire des commandes : description courte, synopsis et options.
   Sert au correcteur (explication des erreurs) et aux pages `man` du terminal simulé. */
(function () {
  'use strict';
  const APP = (window.APP = window.APP || {});
  // nom: [description, synopsis, {option: description}]
  APP.CMD = {
    pwd: ['affiche le répertoire courant (print working directory)', 'pwd', {}],
    cd: ['change de répertoire courant (sans argument ou avec ~ : retour au répertoire personnel ; .. : répertoire parent ; - : répertoire précédent)', 'cd [répertoire]', {}],
    ls: ["liste le contenu d'un répertoire", 'ls [-lahRd] [fichier...]', { l: 'format long (type, droits, liens, propriétaire, groupe, taille, date)', a: 'affiche aussi les fichiers cachés (dont le nom commence par .)', h: 'tailles lisibles (K, M, G), avec -l', R: 'récursif : liste aussi tous les sous-répertoires', d: 'affiche le répertoire lui-même et non son contenu', t: 'trie par date de modification', S: 'trie par taille', r: 'inverse l\'ordre de tri', i: "affiche le numéro d'inode", '1': 'un nom par ligne', color: 'affichage coloré', F: 'ajoute un indicateur de type (/ pour les répertoires)' }],
    mkdir: ['crée un ou plusieurs répertoires vides', 'mkdir [-p] répertoire...', { p: 'crée aussi les répertoires parents manquants, sans erreur s\'il existe déjà', v: 'mode verbeux', m: 'fixe les droits du répertoire créé' }],
    rmdir: ['supprime un répertoire VIDE', 'rmdir répertoire...', { p: 'supprime aussi les parents devenus vides' }],
    touch: ["crée un fichier vide (ou met à jour la date d'un fichier existant)", 'touch fichier...', {}],
    rm: ['supprime des fichiers (et des répertoires avec -r)', 'rm [-rfi] fichier...', { r: 'récursif : supprime un répertoire et tout son contenu', f: 'force : pas de confirmation ni d\'erreur si absent', i: 'demande une confirmation avant chaque suppression', v: 'mode verbeux' }],
    cp: ['copie des fichiers (et des répertoires avec -r) ; la source reste en place', 'cp [-ri] source... destination', { r: 'récursif : copie un répertoire et tout son contenu', i: 'demande confirmation avant d\'écraser', p: 'conserve droits et dates', v: 'mode verbeux', a: 'archive (récursif + conserve tout)' }],
    mv: ['déplace ou renomme un fichier ou un répertoire (la source disparaît)', 'mv [-i] source... destination', { i: "demande confirmation avant d'écraser", v: 'mode verbeux', f: 'écrase sans demander' }],
    cat: ["affiche tout le contenu d'un ou plusieurs fichiers (concatène)", 'cat [-n] fichier...', { n: 'numérote les lignes' }],
    less: ['affiche un fichier page par page (q pour quitter, / pour chercher)', 'less fichier', {}],
    more: ['affiche un fichier page par page', 'more fichier', {}],
    head: ['affiche les premières lignes (10 par défaut)', 'head [-n N] fichier', { n: 'nombre de lignes à afficher', c: "nombre d'octets à afficher" }],
    tail: ['affiche les dernières lignes (10 par défaut)', 'tail [-n N] [-f] fichier', { n: 'nombre de lignes à afficher', f: 'suit le fichier en direct (logs)', c: "nombre d'octets" }],
    wc: ['compte lignes, mots et octets', 'wc [-lwc] [fichier]', { l: 'compte les lignes', w: 'compte les mots', c: 'compte les octets', m: 'compte les caractères' }],
    grep: ['affiche les lignes contenant un motif', 'grep [-inrcvw] motif [fichier...]', { i: 'ignore la casse (majuscules/minuscules)', n: 'affiche le numéro de chaque ligne trouvée', c: 'affiche seulement le nombre de lignes trouvées', v: 'inverse : lignes ne contenant PAS le motif', r: 'récursif dans les répertoires', w: 'mot entier seulement', l: 'affiche seulement les noms de fichiers', E: 'expressions régulières étendues', q: 'silencieux (code de retour seulement)', o: 'affiche seulement la partie trouvée', e: 'motif (utile s\'il commence par -)' }],
    find: ['recherche des fichiers dans une arborescence selon des critères', 'find [répertoire...] [-name motif] [-type f|d] [-perm mode] [-user nom]', { name: 'nom (jokers autorisés, entre guillemets)', iname: 'nom, sans tenir compte de la casse', type: 'type : f fichier, d répertoire, l lien', perm: 'droits (-mode = au moins ces droits)', user: 'propriétaire', group: 'groupe', size: 'taille', maxdepth: 'profondeur maximale', empty: 'fichiers/répertoires vides', exec: 'exécute une commande sur chaque résultat', '!': 'négation du critère suivant' }],
    echo: ['affiche un texte (ou le contenu de variables)', 'echo [-n] [-e] texte...', { n: 'pas de retour à la ligne final', e: 'interprète \\n, \\t…' }],
    man: ["affiche le manuel d'une commande (q pour quitter)", 'man commande', {}],
    whoami: ['affiche votre identifiant (login)', 'whoami', {}],
    who: ['liste les utilisateurs connectés', 'who', {}],
    w: ['liste les utilisateurs connectés et ce qu\'ils font', 'w', {}],
    id: ['affiche UID, GID et groupes d\'un utilisateur', 'id [utilisateur]', {}],
    groups: ['affiche les groupes d\'un utilisateur', 'groups [utilisateur]', {}],
    getent: ['interroge les bases du système (passwd, group, hosts)', 'getent base [clé]', {}],
    history: ['affiche l\'historique numéroté des commandes (!n la rappelle)', 'history', {}],
    alias: ['crée un raccourci de commande (sans espace autour du =)', "alias nom='commande'", {}],
    unalias: ['supprime un alias', 'unalias nom', {}],
    tar: ['archive plusieurs fichiers en un seul (tape archive)', 'tar -cvf archive.tar fichiers… | tar -xvf archive.tar | tar -tf archive.tar', { c: 'crée une archive', x: 'extrait une archive', t: "liste le contenu d'une archive sans l'extraire", v: 'verbeux : affiche les fichiers traités', f: "nom du fichier d'archive (suivi du nom)", z: 'compresse/décompresse avec gzip (.tar.gz)', j: 'compression bzip2', C: "répertoire de destination pour l'extraction" }],
    gcc: ['compile un programme C', 'gcc source.c -o executable', { o: "nom du fichier exécutable produit", Wall: 'affiche tous les avertissements', c: 'compile sans éditer les liens', g: 'informations de débogage' }],
    date: ['affiche la date (format personnalisable avec +%…)', 'date [+FORMAT]', {}],
    diff: ['compare deux fichiers (ou répertoires avec -r)', 'diff [-r] fichier1 fichier2', { r: 'compare récursivement deux répertoires', q: 'indique seulement si les fichiers diffèrent' }],
    df: ["affiche l'espace disque des partitions", 'df [-h]', { h: 'tailles lisibles (K, M, G)', T: 'type de système de fichiers' }],
    du: ["affiche l'espace occupé par des fichiers/répertoires", 'du [-sh] [fichier...]', { s: 'total seulement (summary)', h: 'tailles lisibles', a: 'tous les fichiers', d: 'profondeur max' }],
    sort: ['trie les lignes', 'sort [-hnr] [fichier]', { h: 'trie les tailles lisibles (2K < 1M < 1G)', n: 'tri numérique', r: 'ordre inverse', u: 'supprime les doublons', k: 'clé (colonne) de tri', t: 'séparateur de colonnes' }],
    uniq: ['supprime les lignes consécutives identiques', 'uniq [-c]', { c: 'compte les occurrences' }],
    cut: ['extrait des colonnes', 'cut -d SEP -f N', { d: 'séparateur', f: 'champ(s) à extraire', c: 'caractères' }],
    tee: ["écrit l'entrée à la fois à l'écran et dans un fichier", 'tee [-a] fichier', { a: 'ajoute au lieu d\'écraser' }],
    tree: ["affiche l'arborescence sous forme d'arbre (paquet tree)", 'tree [répertoire]', { a: 'fichiers cachés', d: 'répertoires seulement', L: 'profondeur' }],
    nano: ['éditeur de texte en terminal (Ctrl+O enregistrer, Ctrl+X quitter, Ctrl+W chercher)', 'nano fichier', {}],
    gedit: ['éditeur de texte graphique', 'gedit [fichier]', {}],
    clear: ["efface l'écran du terminal", 'clear', {}],
    exit: ['quitte le shell courant (ou la session SSH)', 'exit [code]', {}],
    sudo: ["exécute une commande avec les droits root (administrateur)", 'sudo commande', { l: 'liste vos droits sudo', u: 'exécute en tant qu\'un autre utilisateur', i: 'ouvre un shell root' }],
    su: ["ouvre une session sous un autre compte (son mot de passe est demandé)", 'su - utilisateur', { l: 'shell de connexion : charge l\'environnement complet (équivaut à -)' }],
    apt: ['gestionnaire de paquets Debian/Ubuntu', 'apt update | upgrade | install P | remove P | purge P | search mot | show P', { y: 'répond oui automatiquement' }],
    dpkg: ['gestionnaire de paquets bas niveau', 'dpkg -L paquet | dpkg -l', { L: 'liste les fichiers installés par un paquet', l: 'liste les paquets installés' }],
    adduser: ['crée un utilisateur avec son répertoire personnel (interactif)', 'sudo adduser nom', {}],
    useradd: ['crée un utilisateur (bas niveau)', 'sudo useradd [-m] nom', { m: 'crée le répertoire personnel', G: 'groupes secondaires', s: 'shell' }],
    deluser: ["supprime un utilisateur (ou le retire d'un groupe : deluser user groupe)", 'sudo deluser [--remove-home] nom [groupe]', { 'remove-home': 'supprime aussi son répertoire personnel' }],
    userdel: ['supprime un utilisateur (bas niveau)', 'sudo userdel [-r] nom', { r: 'supprime le répertoire personnel' }],
    passwd: ['change un mot de passe (ou verrouille un compte)', 'passwd [-l|-u] [utilisateur]', { l: 'verrouille le compte (lock)', u: 'déverrouille le compte', S: 'état du mot de passe', d: 'supprime le mot de passe' }],
    groupadd: ['crée un groupe', 'sudo groupadd groupe', {}],
    groupdel: ['supprime un groupe', 'sudo groupdel groupe', {}],
    usermod: ['modifie un compte utilisateur', 'sudo usermod -aG groupe utilisateur', { a: 'append : AJOUTE aux groupes existants (à combiner avec -G)', G: 'liste des groupes secondaires (sans -a : REMPLACE tous les groupes secondaires)', g: 'groupe principal', L: 'verrouille le compte', U: 'déverrouille le compte', s: 'shell de connexion', d: 'répertoire personnel', l: 'nouveau login' }],
    gpasswd: ['administre un groupe', 'gpasswd -a utilisateur groupe | -d utilisateur groupe', { a: 'ajoute un membre', d: 'retire un membre' }],
    newgrp: ['ouvre un nouveau shell qui tient compte d\'un groupe (fraîchement ajouté)', 'newgrp groupe', {}],
    chmod: ['modifie les droits d\'un fichier (propriétaire ou root)', 'chmod [-R] mode fichier… (mode : u+x, g-w, o=, 640…)', { R: 'récursif : le répertoire et tout son contenu' }],
    chown: ['change le propriétaire (et éventuellement le groupe) — root uniquement', 'sudo chown [-R] utilisateur[:groupe] fichier…', { R: 'récursif' }],
    chgrp: ['change le groupe propriétaire (propriétaire membre du groupe, ou root)', 'chgrp [-R] groupe fichier…', { R: 'récursif' }],
    umask: ['affiche ou fixe le masque des droits retirés à la création', 'umask [-S] [masque]', { S: 'affichage symbolique (droits conservés)' }],
    ps: ['affiche une « photo » des processus', 'ps | ps aux | ps -ef | ps -u user | ps -p PID | ps -o colonnes', { e: 'tous les processus', f: 'format complet (avec PPID)', l: 'format long (F, S, UID, PID, PPID, PRI, NI…)', o: 'choisit les colonnes affichées', p: 'sélectionne par PID', u: 'sélectionne par utilisateur (avec tiret)', C: 'sélectionne par nom de commande', sort: 'trie (ex. --sort=-%cpu)', ppid: 'sélectionne par PID parent', 'B_a': 'a (BSD) : processus de tous les utilisateurs', 'B_u': 'u (BSD) : format orienté utilisateur (USER, %CPU, %MEM…)', 'B_x': 'x (BSD) : inclut les processus sans terminal' }],
    top: ['affiche les processus en temps réel (P tri CPU, M tri mémoire, k tuer, q quitter)', 'top', {}],
    htop: ['version interactive de top (F9 tuer, F10 quitter)', 'htop', {}],
    pstree: ["affiche l'arbre des processus (parents/enfants)", 'pstree [-p] [PID]', { p: 'affiche les PID' }],
    pgrep: ['affiche le PID des processus dont le nom correspond', 'pgrep [-f] [-u user] nom', { f: 'cherche dans la ligne de commande complète', u: 'utilisateur', l: 'affiche aussi le nom' }],
    kill: ['envoie un signal à un processus (SIGTERM par défaut)', 'kill [-SIGNAL] PID… | kill -l', { l: 'liste les signaux', s: 'signal à envoyer', sig: 'signal envoyé' }],
    pkill: ['envoie un signal aux processus dont le nom correspond', 'pkill [-SIGNAL] [-f] [-u user] motif', { f: 'motif cherché dans toute la ligne de commande', u: 'processus de cet utilisateur', x: 'nom exact', sig: 'signal envoyé' }],
    killall: ['tue tous les processus portant exactement ce nom', 'killall [-SIGNAL] nom', { u: 'utilisateur', i: 'confirmation', sig: 'signal envoyé' }],
    jobs: ['liste les tâches (jobs) du terminal courant', 'jobs [-l]', { l: 'affiche aussi les PID' }],
    fg: ['ramène un job au premier plan', 'fg [%n]', {}],
    bg: ['relance un job suspendu en arrière-plan', 'bg [%n]', {}],
    nohup: ['lance une commande qui survit à la fermeture du terminal (ignore SIGHUP)', 'nohup commande &', {}],
    nice: ['lance une commande avec une priorité donnée (-20 haute … 19 basse)', 'nice -n N commande', { n: 'valeur nice (ajout de priorité)' }],
    renice: ["modifie la priorité d'un processus existant", 'renice -n N -p PID', { n: 'nouvelle valeur nice', p: 'PID visé', u: 'tous les processus d\'un utilisateur' }],
    sleep: ['attend N secondes', 'sleep N', {}],
    yes: ['affiche « y » en boucle (utile pour tester la charge CPU)', 'yes', {}],
    taskset: ['fixe le(s) cœur(s) de processeur utilisés', 'taskset -c N commande', { c: 'liste de cœurs' }],
    systemctl: ['gère les services (démons) systemd', 'systemctl status|start|stop|restart|enable|disable|is-enabled service', { now: 'avec enable/disable : démarre/arrête aussi immédiatement' }],
    service: ['gère un service (ancienne syntaxe)', 'service nom start|stop|restart|status', {}],
    journalctl: ['consulte le journal systemd', 'journalctl [-u service] [-f] [--since …]', { u: 'unité (service) à afficher', f: 'suit le journal en direct', since: 'depuis (today, "10 min ago"…)', n: 'nombre de lignes', p: 'priorité' }],
    ip: ['affiche/configure le réseau (remplace ifconfig et route)', 'ip a | ip link | ip route | ip addr add IP/masque dev IF', {}],
    ping: ['teste la joignabilité d\'une machine (ICMP)', 'ping [-c N] machine', { c: 'nombre de paquets à envoyer', i: 'intervalle', W: 'délai d\'attente' }],
    traceroute: ['affiche les routeurs traversés jusqu\'à une machine', 'traceroute machine', {}],
    dig: ['interroge un serveur DNS', 'dig [+short] nom', { '+short': 'réponse courte (adresse seulement)' }],
    nslookup: ['interroge un serveur DNS', 'nslookup nom', {}],
    host: ['résout un nom via le DNS', 'host nom', {}],
    hostname: ['affiche le nom de la machine', 'hostname [-I]', { I: 'adresses IP' }],
    hostnamectl: ['affiche ou change le nom d\'hôte', 'hostnamectl [set-hostname nom]', {}],
    ss: ['affiche les sockets (ports ouverts) — remplace netstat', 'ss -tulpn', { t: 'TCP', u: 'UDP', l: 'ports en écoute (listen)', p: 'processus associé (sudo pour tout voir)', n: 'numérique : ports et adresses non résolus', a: 'toutes les sockets' }],
    curl: ['effectue une requête HTTP (tester un serveur web)', 'curl [-I] URL', { I: 'en-têtes de la réponse seulement', s: 'silencieux', o: 'fichier de sortie', L: 'suit les redirections' }],
    dhclient: ['demande une adresse au serveur DHCP', 'sudo dhclient interface', { r: 'libère le bail' }],
    nmcli: ['pilote NetworkManager', 'nmcli device status', {}],
    ssh: ['ouvre une session chiffrée sur une machine distante', 'ssh [-p port] utilisateur@machine [commande]', { p: 'port (si différent de 22)', i: 'clé privée à utiliser', L: 'tunnel local port:hôte:port', o: 'option de configuration', v: 'verbeux' }],
    scp: ['copie des fichiers via SSH', 'scp [-r] [-P port] source destination (user@machine:chemin)', { r: 'récursif', P: 'port (P MAJUSCULE pour scp)', i: 'clé privée' }],
    'ssh-keygen': ['génère une paire de clés SSH', 'ssh-keygen -t ed25519', { t: 'type de clé (ed25519, rsa…)', b: 'taille en bits', C: 'commentaire', f: 'fichier de sortie' }],
    'ssh-copy-id': ['copie votre clé publique dans ~/.ssh/authorized_keys du serveur', 'ssh-copy-id utilisateur@machine', { i: 'fichier de clé' }],
    sshd: ['démon du serveur SSH', 'sudo sshd -t', { t: 'teste la syntaxe de /etc/ssh/sshd_config' }],
    ufw: ['pare-feu simplifié (Uncomplicated Firewall)', 'ufw default deny incoming | allow ssh | allow 80/tcp | enable | status [numbered|verbose] | delete N', {}],
    'fail2ban-client': ['pilote fail2ban (bannissement des IP qui échouent trop)', 'fail2ban-client status sshd | set sshd unbanip IP', {}],
    chage: ["gère l'expiration des mots de passe", 'sudo chage -M 90 utilisateur | chage -l utilisateur', { M: 'nombre maximal de jours de validité', l: 'affiche la politique d\'expiration', m: 'nombre minimal de jours', W: 'jours d\'avertissement' }],
    visudo: ['édite /etc/sudoers en vérifiant la syntaxe', 'sudo visudo', {}],
    last: ['affiche les dernières connexions réussies', 'last', {}],
    lastb: ['affiche les dernières tentatives de connexion échouées', 'sudo lastb', {}],
    reboot: ['redémarre la machine', 'sudo reboot', {}],
    tcpdump: ['capture le trafic réseau', 'sudo tcpdump -i any -A port N', { i: 'interface (any = toutes)', A: 'affiche le contenu en ASCII', n: 'pas de résolution de noms' }],
    python3: ['interpréteur Python (python3 -m http.server PORT lance un petit serveur web)', 'python3 -m http.server [port]', { m: 'module à exécuter' }],
    bash: ['lance un nouveau shell bash (ou exécute un script)', 'bash [script.sh] | bash -c "commandes"', { c: 'exécute la chaîne de commandes' }],
    source: ['exécute un fichier dans le shell courant (recharger ~/.bashrc)', 'source fichier', {}],
    export: ["définit une variable d'environnement", 'export NOM=valeur', {}],
    which: ['indique le chemin d\'une commande', 'which commande', {}],
    type: ['indique la nature d\'une commande (alias, interne, fichier)', 'type commande', {}],
    uptime: ['depuis quand la machine tourne et sa charge', 'uptime', {}],
    uname: ['informations sur le système/noyau', 'uname [-a] [-r]', { a: 'tout', r: 'version du noyau' }],
    free: ['mémoire vive libre/utilisée', 'free [-h]', { h: 'tailles lisibles' }],
    trap: ["intercepte un signal dans un script", "trap 'commande' SIGNAL", {}],
    exec: ['remplace le shell courant par la commande (même PID)', 'exec commande', {}],
    test: ['évalue une condition (aussi écrit [ … ])', '[ -f fichier ]', {}],
    ln: ['crée un lien', 'ln -s cible nom', { s: 'lien symbolique' }],
    stat: ["affiche les informations détaillées d'un fichier", 'stat fichier', {}],
    xclock: ['affiche une horloge graphique (x11-apps)', 'xclock', {}],
    firefox: ['navigateur web', 'firefox', {}],
    true: ['ne fait rien et réussit (code 0)', 'true', {}],
    false: ['ne fait rien et échoue (code 1)', 'false', {}],
    env: ["affiche les variables d'environnement", 'env', {}],
    printenv: ["affiche les variables d'environnement", 'printenv [VAR]', {}]
  };
  APP.CMD.vi = ['éditeur de texte (dans ce simulateur : utilise nano)', 'vi fichier', {}];
  APP.CMD.vim = APP.CMD.vi;
  APP.CMD.kwrite = APP.CMD.gedit;
  APP.CMD.mousepad = APP.CMD.gedit;
  APP.CMD['apt-get'] = APP.CMD.apt;
  APP.CMD.ifconfig = ['ancienne commande réseau, remplacée par ip (paquet net-tools)', 'ifconfig', {}];
  APP.CMD.netstat = ['ancienne commande, remplacée par ss (paquet net-tools)', 'netstat -tulpn', {}];

  APP.SIGNALS = { HUP: 1, INT: 2, QUIT: 3, ILL: 4, TRAP: 5, ABRT: 6, BUS: 7, FPE: 8, KILL: 9, USR1: 10, SEGV: 11, USR2: 12, PIPE: 13, ALRM: 14, TERM: 15, STKFLT: 16, CHLD: 17, CONT: 18, STOP: 19, TSTP: 20, TTIN: 21, TTOU: 22 };
  APP.SIGNAME = {}; for (const k in APP.SIGNALS) APP.SIGNAME[APP.SIGNALS[k]] = k;
  APP.SIGDESC = { 1: 'SIGHUP : terminal fermé / relire la configuration', 2: 'SIGINT : interruption (Ctrl+C)', 9: 'SIGKILL : arrêt immédiat et forcé (non interceptable)', 15: 'SIGTERM : arrêt propre (signal par défaut de kill)', 18: 'SIGCONT : reprendre un processus suspendu', 19: 'SIGSTOP : suspendre (non interceptable)', 20: 'SIGTSTP : suspension clavier (Ctrl+Z)' };
})();
